name: ml_explainability
channels:
  - default
  - conda-forge
  - anaconda
dependencies:
  - ipython=7.12.0
  - flake8
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - rise=5.6.1
  - numpy=1.19.2
  - pandas=1.1.3
  - pyarrow=0.17.1
  - python=3.8.6
  - scikit-learn=0.23.1
  - matplotlib=3.3.0
  - plotly=4.8.2
  - scikit-learn=0.23.1
  - seaborn=0.11.0
  - pip=20.1.1
  - pip:
    - eli5==0.10.1
    - shap==0.36.0
    - PDPbox==0.2.0
